version: "3.3"
services:
  reverse-proxy:
    image: traefik:v2.4
    command:
      - "--api.insecure=false"
      # - "--log.level=DEBUG"
      - "--api.dashboard=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=decodestudios.help@gmail.com"
      # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  db:
    image: redis
    restart: always
  next:
    build: .
    restart: always
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
        # - "traefik.http.middlewares.myredirect.scheme=https"
        # - "traefik.http.routers.nextjs.middlewares=myredirect"
      - "traefik.http.routers.nextjs.rule=Host(`f-st.ga`, `www.f-st.ga`)"
      - "traefik.http.routers.nextjs.entrypoints=web"
      - "traefik.http.routers.nextjssecure.rule=Host(`f-st.ga`, `www.f-st.ga`)"
      - "traefik.http.routers.nextjssecure.entrypoints=websecure"
      - "traefik.http.routers.nextjssecure.tls.certresolver=myresolver"
      - "traefik.http.routers.nextjssecure.tls=true"
