version: "3.9"
services:
  db:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  next:
    build: .
    restart: always
    environment:
      - REDIS_HOST=db
    ports:
      - "3000:3000"
